version: '2'
services:
  freepbx:
#    build: .
    image: igormeshkv/docker-freepbx
    container_name: freepbx

    network_mode: "host"

    volumes:
      - freepbx-apache:/etc/apache2
      - freepbx-asterisk-config:/etc/asterisk
      - freepbx-mysql:/var/lib/mysql
      - freepbx-asterisk-spool:/var/spool/asterisk
      - freepbx-asterisk-data:/var/lib/asterisk

volumes:
  freepbx-apache:
  freepbx-asterisk-config:
  freepbx-mysql:
  freepbx-asterisk-spool:
  freepbx-asterisk-data:
